In [12]:
import pandas as pd

In [13]:
customers = pd.read_csv('../Extraction/Landing/customers/customers.csv')
customers

,customer_id,first_name,last_name,phone,email,street,city,state,zip_code,source,timestamp_saved
0,1,Debra,Burks,NaN,debra.burks@yahoo.com,9273 Thorne Ave.,Orchard Park,NY,14127,DL,2024-04-28 17:57:07.056143
1,2,Kasha,Todd,NaN,kasha.todd@yahoo.com,910 Vine Street,Campbell,CA,95008,DL,2024-04-28 17:57:07.056143
2,3,Tameka,Fisher,NaN,tameka.fisher@aol.com,769C Honey Creek St.,Redondo Beach,CA,90278,DL,2024-04-28 17:57:07.056143
3,4,Daryl,Spence,NaN,daryl.spence@aol.com,988 Pearl Lane,Uniondale,NY,11553,DL,2024-04-28 17:57:07.056143
4,5,Charolette,Rice,(916) 381-6003,charolette.rice@msn.com,107 River Dr.,Sacramento,CA,95820,DL,2024-04-28 17:57:07.056143
...,...,...,...,...,...,...,...,...,...,...,...
1440,1441,Jamaal,Morrison,NaN,jamaal.morrison@msn.com,796 SE. Nut Swamp St.,Staten Island,NY,10301,DL,2024-04-28 17:57:07.056143
1441,1442,Cassie,Cline,NaN,cassie.cline@gmail.com,947 Lafayette Drive,Brooklyn,NY,11201,DL,2024-04-28 17:57:07.056143
1442,1443,Lezlie,Lamb,NaN,lezlie.lamb@gmail.com,401 Brandywine Street,Central Islip,NY,11722,DL,2024-04-28 17:57:07.056143
1443,1444,Ivette,Estes,NaN,ivette.estes@gmail.com,88 N. Canterbury Ave.,Canandaigua,NY,14424,DL,2024-04-28 17:57:07.056143
1444,1445,Ester,Acevedo,NaN,ester.acevedo@gmail.com,671 Miles Court,San Lorenzo,CA,94580,DL,2024-04-28 17:57:07.056143

In [14]:
customers.duplicated().sum()

0

In [15]:
customers.isnull().sum()

customer_id           0
first_name            0
last_name             0
phone              1267
email                 0
street                0
city                  0
state                 0
zip_code              0
source                0
timestamp_saved       0
dtype: int64

In [16]:
customers.to_csv('../staging_1/customers/customers.csv', index = False)