In [1]:
import pandas as pd

In [2]:
products = pd.read_csv('../staging_1/products/products.csv')
products

,product_id,product_name,brand_id,category_id,model_year,list_price,source,timestamp_saved
0,1,Trek 820 - 2016,9,6,2016,379.99,DL,2024-04-28 17:57:15.953684
1,2,Ritchey Timberwolf Frameset - 2016,5,6,2016,749.99,DL,2024-04-28 17:57:15.953684
2,3,Surly Wednesday Frameset - 2016,8,6,2016,999.99,DL,2024-04-28 17:57:15.953684
3,4,Trek Fuel EX 8 29 - 2016,9,6,2016,2899.99,DL,2024-04-28 17:57:15.953684
4,5,Heller Shagamaw Frame - 2016,3,6,2016,1320.99,DL,2024-04-28 17:57:15.953684
...,...,...,...,...,...,...,...,...
316,317,Trek Checkpoint ALR 5 - 2019,9,7,2019,1999.99,DL,2024-04-28 17:57:15.953684
317,318,Trek Checkpoint ALR 5 Women's - 2019,9,7,2019,1999.99,DL,2024-04-28 17:57:15.953684
318,319,Trek Checkpoint SL 5 Women's - 2019,9,7,2019,2799.99,DL,2024-04-28 17:57:15.953684
319,320,Trek Checkpoint SL 6 - 2019,9,7,2019,3799.99,DL,2024-04-28 17:57:15.953684
320,321,Trek Checkpoint ALR Frameset - 2019,9,7,2019,3199.99,DL,2024-04-28 17:57:15.953684

In [4]:
products.to_csv('../staging_2/products/products.csv', index = False)